name = "kommodo-video-worker"
type = "javascript"
account_id = "049b487510d2a5be1122f99fd9ae8bea"
workers_dev = true
compatibility_date = "2026-03-16"

[vars]
ALLOWED_ORIGIN = "http://127.0.0.1:5500"

[env.production.vars]
ALLOWED_ORIGIN = "https://kommodo.osama-abdullah.com"